#!/usr/bin/env sh
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabao --load-sa
echo "YABAI LOADED"

# external bar
yabai -m config external_bar all:0:0.0

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_shadow off
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0

yabai -m rule --add app="^Things.*$" sticky=off manage=off
yabai -m rule --add app="^Google Meet.*$" sticky=off manage=off
yabai -m rule --add app="^Github Desktop.*$" sticky=off manage=off

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# yabai -m signal --add event=display_changed action="python3 ~/.config/yabai/padding.py"
yabai -m signal --add event=display_changed action="python3 ~/.config/yabai/reload-sketchy.sh"

echo "Try to load scripting addition"
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabao --load-sa

echo "yabai configuration loaded.."
