import = ["~/.config/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "MonoLisa Nerd Font"

[font.offset]
y = 3
x = 0

[shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[window]
decorations = "none"
startup_mode = "Maximized" 
opacity = 0.9

[colors]
draw_bold_text_with_bright_colors = true
